# Tên của workflow, sẽ hiển thị trong tab "Actions" trên GitHub
name: Build TuTienPlugin

# Điều kiện để workflow này chạy
on:
  # Chạy mỗi khi có ai đó push code lên nhánh "main"
  push:
    branches: [ "main" ]
  # Cũng cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

# Các công việc (jobs) sẽ được thực hiện
jobs:
  build:
    # Sử dụng một máy ảo Ubuntu mới nhất để chạy
    runs-on: ubuntu-latest

    # Các bước thực hiện
    steps:
      # Bước 1: Lấy mã nguồn từ repository của bạn
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Cài đặt môi trường Java (JDK phiên bản 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Bước 3: Thực hiện build bằng Maven
      # Dòng lệnh 'mvn' sẽ được cài đặt bởi setup-java action
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Bước 4: Tải lên (upload) file .jar đã build thành công
      # File này sẽ được lưu trữ như một "artifact" của workflow
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Tên của artifact, bạn có thể đặt bất kỳ tên gì
          name: TuTienPlugin-Build
          # Đường dẫn đến file .jar cần tải lên
          path: target/*.jar
